package com.rawmakyamu.util.mapping;
// Generated Jul 9, 2016 3:30:33 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AtmLocations generated by hbm2java
 */
@Entity
@Table(name = "ATM_LOCATIONS", uniqueConstraints = @UniqueConstraint(columnNames = "ATM_CODE")
)
public class AtmLocations implements java.io.Serializable {

    private BigDecimal id;
    private Status status;
    private String description;
    private String latitude;
    private String longitude;
    private Date createTime;
    private Date lastupdatedTime;
    private String atmCode;
    private String address;
    private Status statusByIsAtm;
    private Status statusByIsCdm;
    private Status statusByIsBranch;
    private Status statusByIsAgent;
    private Status statusByIsShop;

    public AtmLocations() {
    }

    public AtmLocations(BigDecimal id, String atmCode) {
        this.id = id;
        this.atmCode = atmCode;
    }

    public AtmLocations(BigDecimal id, Status status, String description, String latitude, String longitude, Date createTime,
            Date lastupdatedTime, String atmCode, String address,
            Status statusByIsAtm, Status statusByIsCdm, Status statusByIsBranch, Status statusByIsAgent,
            Status statusByIsShop) {
        this.id = id;
        this.status = status;
        this.description = description;
        this.latitude = latitude;
        this.longitude = longitude;
        this.createTime = createTime;
        this.lastupdatedTime = lastupdatedTime;
        this.atmCode = atmCode;
        this.address = address;
        this.statusByIsAtm = statusByIsAtm;
        this.statusByIsCdm = statusByIsCdm;
        this.statusByIsBranch = statusByIsBranch;
        this.statusByIsAgent = statusByIsAgent;
        this.statusByIsShop = statusByIsShop;

    }

    @Id

    @SequenceGenerator(name = "SequenceIdGenerator", sequenceName = "ATM_LOCATIONS_SEQ")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SequenceIdGenerator")

    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUS")
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @Column(name = "DESCRIPTION", length = 128)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "LATITUDE", length = 128)
    public String getLatitude() {
        return this.latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    @Column(name = "LONGITUDE", length = 128)
    public String getLongitude() {
        return this.longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_TIME", length = 23)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "LASTUPDATED_TIME", length = 7)
    public Date getLastupdatedTime() {
        return this.lastupdatedTime;
    }

    public void setLastupdatedTime(Date lastupdatedTime) {
        this.lastupdatedTime = lastupdatedTime;
    }

    @Column(name = "ATM_CODE", unique = true, nullable = false, length = 20)
    public String getAtmCode() {
        return this.atmCode;
    }

    public void setAtmCode(String atmCode) {
        this.atmCode = atmCode;
    }

    @Column(name = "ADDRESS")
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "IS_ATM")
    public Status getStatusByIsAtm() {
        return this.statusByIsAtm;
    }

    public void setStatusByIsAtm(Status statusByIsAtm) {
        this.statusByIsAtm = statusByIsAtm;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "IS_CDM")
    public Status getStatusByIsCdm() {
        return this.statusByIsCdm;
    }

    public void setStatusByIsCdm(Status statusByIsCdm) {
        this.statusByIsCdm = statusByIsCdm;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "IS_BRANCH")
    public Status getStatusByIsBranch() {
        return this.statusByIsBranch;
    }

    public void setStatusByIsBranch(Status statusByIsBranch) {
        this.statusByIsBranch = statusByIsBranch;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "IS_AGENT")
    public Status getStatusByIsAgent() {
        return this.statusByIsAgent;
    }

    public void setStatusByIsAgent(Status statusByIsAgent) {
        this.statusByIsAgent = statusByIsAgent;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "IS_SHOP")
    public Status getStatusByIsShop() {
        return this.statusByIsShop;
    }

    public void setStatusByIsShop(Status statusByIsShop) {
        this.statusByIsShop = statusByIsShop;
    }

}
