package com.rawmakyamu.util.mapping;
// Generated Jan 28, 2016 9:45:39 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Page generated by hbm2java
 */
@Entity
@Table(name="CURRENCY"
    
    
)
public class Currency  implements java.io.Serializable {


     private String currencycode;     
     private String description;     
     private String isocode;     
     


    public Currency() {
    }

	
    public Currency(String currencycode) {
        this.currencycode = currencycode;
    }
    public Currency(String currencycode, String isocode, String description) {
       this.currencycode = currencycode;
       this.description = description; 
       this.isocode=isocode;
    }
   
     @Id 
    @Column(name="CURRENCYCODE", unique=true, nullable=false, length=5)
      public String getCurrencycode() {
        return currencycode;
    }

    public void setCurrencycode(String currencycode) {
        this.currencycode = currencycode;
    }
    
    @Column(name="DESCRIPTION", length=50)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }


    @Column(name="ISOCODE", length=5)
    public String getIsocode() {
        return isocode;
    }

    public void setIsocode(String isocode) {
        this.isocode = isocode;
    }

}


