package com.rawmakyamu.util.mapping;
// Generated Jan 28, 2016 9:45:39 AM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Loginhistory generated by hbm2java
 */
@Entity
@Table(name = "MS_LOGINHISTORY"
)
public class Loginhistory implements java.io.Serializable {

    private String historyid;
//     private String customerid;
    private String walletid;
    private String pushid;
    private String mobilenumber;
    private String sessionkey;
    private String XCoordinate;
    private String YCoordinate;
    private Date loggedtime;
    private Status status;
    private Task task;
    private Logintype logintype;
    private String nic;

    public Loginhistory() {
    }

    public Loginhistory(String historyid, String walletid, String mobilenumber) {
        this.historyid = historyid;
        this.walletid = walletid;
//        this.customerid=customerid;
        this.mobilenumber = mobilenumber;
    }

    public Loginhistory(String nic, String mobilenumber, String historyid, String walletid, String pushid, String sessionkey, String XCoordinate, String YCoordinate, Date loggedtime, Status status, Task task,Logintype logintype) {
        this.historyid = historyid;
        this.walletid = walletid;
        this.pushid = pushid;
        this.sessionkey = sessionkey;
        this.XCoordinate = XCoordinate;
        this.YCoordinate = YCoordinate;
        this.loggedtime = loggedtime;
        this.status = status;
        this.logintype = logintype;
//       this.customerid=customerid;
        this.mobilenumber = mobilenumber;
        this.nic = nic;
        this.task = task;
    }

    @Id

    @Column(name = "HISTORYID", unique = true, nullable = false, length = 20)
    public String getHistoryid() {
        return this.historyid;
    }

    public void setHistoryid(String historyid) {
        this.historyid = historyid;
    }

    @Column(name = "MOBILENUMBER", unique = true, nullable = false, length = 20)
    public String getMobilenumber() {
        return mobilenumber;
    }

    public void setMobilenumber(String mobilenumber) {
        this.mobilenumber = mobilenumber;
    }

//    @Column(name="CUSTOMERID", nullable=false, length=50)
//    public String getCustomerid() {
//        return customerid;
//    }
//
//    public void setCustomerid(String customerid) {
//        this.customerid = customerid;
//    }
    @Column(name = "WALLETID", nullable = false, length = 50)
    public String getWalletid() {
        return this.walletid;
    }

    public void setWalletid(String walletid) {
        this.walletid = walletid;
    }

    @Column(name = "PUSHIDSHA")
    public String getPushid() {
        return this.pushid;
    }

    public void setPushid(String pushid) {
        this.pushid = pushid;
    }

    @Column(name = "SESSIONKEY")
    public String getSessionkey() {
        return this.sessionkey;
    }

    public void setSessionkey(String sessionkey) {
        this.sessionkey = sessionkey;
    }

    @Column(name = "LATITUDE", length = 128)
    public String getXCoordinate() {
        return this.XCoordinate;
    }

    public void setXCoordinate(String XCoordinate) {
        this.XCoordinate = XCoordinate;
    }

    @Column(name = "LONGITUDE", length = 128)
    public String getYCoordinate() {
        return this.YCoordinate;
    }

    public void setYCoordinate(String YCoordinate) {
        this.YCoordinate = YCoordinate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LOGGEDTIME", length = 23)
    public Date getLoggedtime() {
        return this.loggedtime;
    }

    public void setLoggedtime(Date loggedtime) {
        this.loggedtime = loggedtime;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUS")
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @Column(name = "NIC", length = 20)

    public String getNic() {
        return nic;
    }

    public void setNic(String nic) {
        this.nic = nic;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "TASK")
    public Task getTask() {
        return task;
    }

    public void setTask(Task task) {
        this.task = task;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TYPE")
    public Logintype getLogintype() {
        return logintype;
    }

    public void setLogintype(Logintype logintype) {
        this.logintype = logintype;
    }

    
    
}
