package com.rawmakyamu.util.mapping;
// Generated Jun 27, 2017 2:19:43 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MsCustomerWalletPushFile generated by hbm2java
 */
@Entity
@Table(name = "MS_CUSTOMER_WALLET_PUSH_FILE"
)
public class MsCustomerWalletPushFile implements java.io.Serializable {

    private BigDecimal id;
    private String fileName;
    private String status;
    private Date createTime;
    private Date lastUpdatedTime;

    public MsCustomerWalletPushFile() {
    }

    public MsCustomerWalletPushFile(BigDecimal id) {
        this.id = id;
    }

    public MsCustomerWalletPushFile(BigDecimal id, String fileName, String status, Date createTime, Date lastUpdatedTime) {
        this.id = id;
        this.fileName = fileName;
        this.status = status;
        this.createTime = createTime;
        this.lastUpdatedTime = lastUpdatedTime;
    }

    @Id
    @SequenceGenerator(name = "SequenceIdGenerator", sequenceName = "MS_CUSTOMER_WALLET_PUSH_FILE_")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SequenceIdGenerator")

    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @Column(name = "FILE_NAME", length = 128)
    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    @Column(name = "STATUS", length = 5)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_TIME", length = 7)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LAST_UPDATED_TIME", length = 7)
    public Date getLastUpdatedTime() {
        return this.lastUpdatedTime;
    }

    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

}
