package com.rawmakyamu.util.mapping;
// Generated Jul 9, 2016 3:30:33 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MsPromotions generated by hbm2java
 */
@Entity
@Table(name = "MS_PROMOTIONS"
)
public class MsPromotions implements java.io.Serializable {

    private BigDecimal promotionId;
    private String title;
    private String description;
    private String tabImgName;
    private String mobImgName;
    private String pageUrl;
    private BigDecimal clickCount = new BigDecimal(BigInteger.ZERO);
    private BigDecimal likeCount = new BigDecimal(BigInteger.ZERO);
    private BigDecimal shareCount = new BigDecimal(BigInteger.ZERO);
    private Date expDate;
    private Status status;
    private Integer sortOrder;
    private Integer shareAttemptCount;
    private BigDecimal updateSequence = new BigDecimal(BigInteger.ZERO);
    private Date createTime;
    private Date updatedTime;
    private Date startDate;
    private Promotionuserlevel userLevel;
    private byte[] tabimg;
    private byte[] mobimg;
    private Date imgId;

    public MsPromotions() {
    }

    public MsPromotions(BigDecimal promotionId, Date createTime, BigDecimal clickCount, BigDecimal likeCount, BigDecimal shareCount, BigDecimal updateSequence) {
        this.promotionId = promotionId;
        this.createTime = createTime;
        this.clickCount = clickCount;
        this.likeCount = likeCount;
        this.shareCount = shareCount;
        this.updateSequence = updateSequence;
    }

    public MsPromotions(Promotionuserlevel userLevel,BigDecimal promotionId, String title, String description, String tabImgName, String mobImgName, String pageUrl, BigDecimal clickCount, BigDecimal likeCount, BigDecimal shareCount, Date expDate, Status status, Integer sortOrder,Integer shareAttemptCount, BigDecimal updateSequence, Date createTime, Date updatedTime, Date startDate) {
        this.promotionId = promotionId;
        this.title = title;
        this.description = description;
        this.tabImgName = tabImgName;
        this.mobImgName = mobImgName;
        this.pageUrl = pageUrl;
        this.clickCount = clickCount;
        this.likeCount = likeCount;
        this.shareCount = shareCount;
        this.expDate = expDate;
        this.status = status;
        this.sortOrder = sortOrder;
        this.shareAttemptCount = shareAttemptCount;
        this.updateSequence = updateSequence;
        this.createTime = createTime;
        this.updatedTime = updatedTime;
        this.startDate = startDate;
        this.userLevel=userLevel;
    }

    @Id

    @Column(name = "PROMOTION_ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getPromotionId() {
        return this.promotionId;
    }

    public void setPromotionId(BigDecimal promotionId) {
        this.promotionId = promotionId;
    }

    @Column(name = "TITLE", length = 100)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "DESCRIPTION", length = 200)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "PAGE_URL", length = 200)
    public String getPageUrl() {
        return this.pageUrl;
    }

    public void setPageUrl(String pageUrl) {
        this.pageUrl = pageUrl;
    }

    @Column(name = "CLICK_COUNT", nullable = false, columnDefinition = "int default 0", precision = 22, scale = 0)
    public BigDecimal getClickCount() {
        return this.clickCount;
    }

    public void setClickCount(BigDecimal clickCount) {
        this.clickCount = clickCount;
    }

    @Column(name = "LIKE_COUNT", nullable = false, columnDefinition = "int default 0", precision = 22, scale = 0)
    public BigDecimal getLikeCount() {
        return this.likeCount;
    }

    public void setLikeCount(BigDecimal likeCount) {
        this.likeCount = likeCount;
    }

    @Column(name = "SHARE_COUNT", nullable = false, columnDefinition = "int default 0", precision = 22, scale = 0)
    public BigDecimal getShareCount() {
        return this.shareCount;
    }

    public void setShareCount(BigDecimal shareCount) {
        this.shareCount = shareCount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "EXP_DATE", length = 23)
    public Date getExpDate() {
        return this.expDate;
    }

    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUS")
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @Column(name = "SORT_ORDER", precision = 5, scale = 0)
    public Integer getSortOrder() {
        return this.sortOrder;
    }

    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }
    @Column(name = "SHARE_ATTEMPT_COUNT" ,precision = 2, scale = 0)
    public Integer getShareAttemptCount() {
        return this.shareAttemptCount;
    }

    public void setShareAttemptCount(Integer shareAttemptCount) {
        this.shareAttemptCount = shareAttemptCount;
    }

    @Column(name = "UPDATE_SEQUENCE", nullable = false, columnDefinition = "int default 0", precision = 22, scale = 0)
    public BigDecimal getUpdateSequence() {
        return this.updateSequence;
    }

    public void setUpdateSequence(BigDecimal updateSequence) {
        this.updateSequence = updateSequence;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_TIME", nullable = false, length = 23)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED_TIME", length = 23)
    public Date getUpdatedTime() {
        return this.updatedTime;
    }

    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "START_DATE", length = 23)
    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "USER_LEVEL")
    public Promotionuserlevel getUserLevel() {
        return userLevel;
    }

    public void setUserLevel(Promotionuserlevel userLevel) {
        this.userLevel = userLevel;
    }

    @Column(name = "TAB_IMG_NAME", length = 200)
    public String getTabImgName() {
        return tabImgName;
    }

    public void setTabImgName(String tabImgName) {
        this.tabImgName = tabImgName;
    }

    @Column(name = "MOB_IMG_NAME", length = 200)
    public String getMobImgName() {
        return mobImgName;
    }

    public void setMobImgName(String mobImgName) {
        this.mobImgName = mobImgName;
    }

    @Column(name = "TAB_IMG")
    public byte[] getTabimg() {
        return tabimg;
    }

    public void setTabimg(byte[] tabimg) {
        this.tabimg = tabimg;
    }

    @Column(name = "MOB_IMG")
    public byte[] getMobimg() {
        return mobimg;
    }

    public void setMobimg(byte[] mobimg) {
        this.mobimg = mobimg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "IMG_ID", length = 23)
    public Date getImgId() {
        return imgId;
    }

    public void setImgId(Date imgId) {
        this.imgId = imgId;
    }

}
