package com.rawmakyamu.util.mapping;
// Generated Jul 9, 2016 3:30:33 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MsUserParam generated by hbm2java
 */
@Entity
@Table(name = "MS_USER_PARAM"
)
public class MsUserParam implements java.io.Serializable {

    private String paramcode;
    private String description;
    private String paramValue;
    private String lastupdateduser;
    private Date lastupdatedtime;
    private Date createdtime;

    public MsUserParam() {
    }

    public MsUserParam(String paramcode, String description, String paramValue) {
        this.paramcode = paramcode;
        this.description = description;
        this.paramValue = paramValue;
    }

    public MsUserParam(String paramcode, String description, String paramValue, String lastupdateduser, Date lastupdatedtime, Date createdtime) {
        this.paramcode = paramcode;
        this.description = description;
        this.paramValue = paramValue;
        this.lastupdateduser = lastupdateduser;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
    }

    @Id

    @Column(name = "PARAMCODE", unique = true, nullable = false, length = 16)
    public String getParamcode() {
        return this.paramcode;
    }

    public void setParamcode(String paramcode) {
        this.paramcode = paramcode;
    }

    @Column(name = "DESCRIPTION", nullable = false, length = 128)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "PARAM_VALUE", nullable = false, length = 1000)
    public String getParamValue() {
        return this.paramValue;
    }

    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }

    @Column(name = "LASTUPDATEDUSER", length = 64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }

    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "LASTUPDATEDTIME", length = 7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }

    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CREATEDTIME", length = 7)
    public Date getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

}
