/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rawmakyamu.util.mapping;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MsUserMessage generated by hbm2java
 */
@Entity
@Table(name = "MS_USER_MESSAGE"
)
public class MsUserMessage implements java.io.Serializable {

    private String paramcode;
    private String description;
    private String paramValue;
    private String lastupdateduser;
    private Date lastupdatedtime;
    private Date createdtime;
    private String msgCategory;

    public MsUserMessage() {
    }

    public MsUserMessage(String paramcode, String paramValue) {
        this.paramcode = paramcode;
        this.paramValue = paramValue;
    }

    public MsUserMessage(String paramcode, String description, String paramValue, String lastupdateduser, Date lastupdatedtime, Date createdtime, String msgCategory) {
        this.paramcode = paramcode;
        this.description = description;
        this.paramValue = paramValue;
        this.lastupdateduser = lastupdateduser;
        this.lastupdatedtime = lastupdatedtime;
        this.createdtime = createdtime;
        this.msgCategory = msgCategory;
    }

    @Id

    @Column(name = "PARAMCODE", unique = true, nullable = false, length = 16)
    public String getParamcode() {
        return this.paramcode;
    }

    public void setParamcode(String paramcode) {
        this.paramcode = paramcode;
    }

    @Column(name = "DESCRIPTION", length = 128)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "PARAM_VALUE", nullable = false, length = 128)
    public String getParamValue() {
        return this.paramValue;
    }

    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }

    @Column(name = "LASTUPDATEDUSER", length = 64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }

    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "LASTUPDATEDTIME", length = 7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }

    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATEDTIME", length = 7)
    public Date getCreatedtime() {
        return this.createdtime;
    }

    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @Column(name = "MSG_CATEGORY", length = 20)
    public String getMsgCategory() {
        return this.msgCategory;
    }

    public void setMsgCategory(String msgCategory) {
        this.msgCategory = msgCategory;
    }

}
