package com.rawmakyamu.util.mapping;
// Generated Oct 10, 2016 6:55:13 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PagetaskTemplate generated by hbm2java
 */
@Entity
@Table(name = "PAGETASK_TEMPLATE")
public class PagetaskTemplate implements java.io.Serializable {

    private PagetaskTemplateId id;
    private Page page;
    private Task task;
    private String lastupdateduser;
    private Date lastupdatedtime;
    private Date createtime;
    private String isDual;

    public PagetaskTemplate() {
    }

    public PagetaskTemplate(PagetaskTemplateId id, Page page, Task task) {
        this.id = id;
        this.page = page;
        this.task = task;
    }

    public PagetaskTemplate(PagetaskTemplateId id, Page page, Task task, String lastupdateduser, Date lastupdatedtime, Date createtime, String isDual) {
        this.id = id;
        this.page = page;
        this.task = task;
        this.lastupdateduser = lastupdateduser;
        this.lastupdatedtime = lastupdatedtime;
        this.createtime = createtime;
        this.isDual = isDual;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "pagecode", column = @Column(name = "PAGECODE", nullable = false, length = 6)),
        @AttributeOverride(name = "taskcode", column = @Column(name = "TASKCODE", nullable = false, length = 6))})
    public PagetaskTemplateId getId() {
        return this.id;
    }

    public void setId(PagetaskTemplateId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PAGECODE", nullable = false, insertable = false, updatable = false)
    public Page getPage() {
        return this.page;
    }

    public void setPage(Page page) {
        this.page = page;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TASKCODE", nullable = false, insertable = false, updatable = false)
    public Task getTask() {
        return this.task;
    }

    public void setTask(Task task) {
        this.task = task;
    }

    @Column(name = "LASTUPDATEDUSER", length = 64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }

    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "LASTUPDATEDTIME", length = 7)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }

    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CREATETIME", length = 7)
    public Date getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    @Column(name = "IS_DUAL", length = 20)
    public String getIsDual() {
        return isDual;
    }

    public void setIsDual(String isDual) {
        this.isDual = isDual;
    }

}
