package com.rawmakyamu.util.mapping;
// Generated Jan 28, 2016 9:45:39 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pagetask generated by hbm2java
 */
@Entity
@Table(name="PAGETASK"
    
    
)
public class Pagetask  implements java.io.Serializable {


     private PagetaskId id;
     private Page page;
     private Userrole userrole;
     private Task task;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createtime;

    public Pagetask() {
    }

	
    public Pagetask(PagetaskId id, Page page, Userrole userrole, Task task) {
        this.id = id;
        this.page = page;
        this.userrole = userrole;
        this.task = task;
    }
    public Pagetask(PagetaskId id, Page page, Userrole userrole, Task task, String lastupdateduser, Date lastupdatedtime, Date createtime) {
       this.id = id;
       this.page = page;
       this.userrole = userrole;
       this.task = task;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createtime = createtime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userrolecode", column=@Column(name="USERROLECODE", nullable=false, length=20) ), 
        @AttributeOverride(name="pagecode", column=@Column(name="PAGECODE", nullable=false, length=20) ), 
        @AttributeOverride(name="taskcode", column=@Column(name="TASKCODE", nullable=false, length=20) ) } )
    public PagetaskId getId() {
        return this.id;
    }
    
    public void setId(PagetaskId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAGECODE", nullable=false, insertable=false, updatable=false)
    public Page getPage() {
        return this.page;
    }
    
    public void setPage(Page page) {
        this.page = page;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERROLECODE", nullable=false, insertable=false, updatable=false)
    public Userrole getUserrole() {
        return this.userrole;
    }
    
    public void setUserrole(Userrole userrole) {
        this.userrole = userrole;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TASKCODE", nullable=false, insertable=false, updatable=false)
    public Task getTask() {
        return this.task;
    }
    
    public void setTask(Task task) {
        this.task = task;
    }

    
    @Column(name="LASTUPDATEDUSER", length=20)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=23)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATETIME", length=23)
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }




}


