package com.rawmakyamu.util.mapping;
// Generated Jan 28, 2016 9:45:39 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PagetaskId generated by hbm2java
 */
@Embeddable
public class PagetaskId  implements java.io.Serializable {


     private String userrolecode;
     private String pagecode;
     private String taskcode;

    public PagetaskId() {
    }

    public PagetaskId(String userrolecode, String pagecode, String taskcode) {
       this.userrolecode = userrolecode;
       this.pagecode = pagecode;
       this.taskcode = taskcode;
    }
   


    @Column(name="USERROLECODE", nullable=false, length=20)
    public String getUserrolecode() {
        return this.userrolecode;
    }
    
    public void setUserrolecode(String userrolecode) {
        this.userrolecode = userrolecode;
    }


    @Column(name="PAGECODE", nullable=false, length=20)
    public String getPagecode() {
        return this.pagecode;
    }
    
    public void setPagecode(String pagecode) {
        this.pagecode = pagecode;
    }


    @Column(name="TASKCODE", nullable=false, length=20)
    public String getTaskcode() {
        return this.taskcode;
    }
    
    public void setTaskcode(String taskcode) {
        this.taskcode = taskcode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PagetaskId) ) return false;
		 PagetaskId castOther = ( PagetaskId ) other; 
         
		 return ( (this.getUserrolecode()==castOther.getUserrolecode()) || ( this.getUserrolecode()!=null && castOther.getUserrolecode()!=null && this.getUserrolecode().equals(castOther.getUserrolecode()) ) )
 && ( (this.getPagecode()==castOther.getPagecode()) || ( this.getPagecode()!=null && castOther.getPagecode()!=null && this.getPagecode().equals(castOther.getPagecode()) ) )
 && ( (this.getTaskcode()==castOther.getTaskcode()) || ( this.getTaskcode()!=null && castOther.getTaskcode()!=null && this.getTaskcode().equals(castOther.getTaskcode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserrolecode() == null ? 0 : this.getUserrolecode().hashCode() );
         result = 37 * result + ( getPagecode() == null ? 0 : this.getPagecode().hashCode() );
         result = 37 * result + ( getTaskcode() == null ? 0 : this.getTaskcode().hashCode() );
         return result;
   }   


}


