package com.rawmakyamu.util.mapping;
// Generated Oct 10, 2016 6:55:13 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PagetaskTemplateId generated by hbm2java
 */
@Embeddable
public class PagetaskTemplateId  implements java.io.Serializable {


     private String pagecode;
     private String taskcode;

    public PagetaskTemplateId() {
    }

    public PagetaskTemplateId(String pagecode, String taskcode) {
       this.pagecode = pagecode;
       this.taskcode = taskcode;
    }
   


    @Column(name="PAGECODE", nullable=false, length=6)
    public String getPagecode() {
        return this.pagecode;
    }
    
    public void setPagecode(String pagecode) {
        this.pagecode = pagecode;
    }


    @Column(name="TASKCODE", nullable=false, length=6)
    public String getTaskcode() {
        return this.taskcode;
    }
    
    public void setTaskcode(String taskcode) {
        this.taskcode = taskcode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PagetaskTemplateId) ) return false;
		 PagetaskTemplateId castOther = ( PagetaskTemplateId ) other; 
         
		 return ( (this.getPagecode()==castOther.getPagecode()) || ( this.getPagecode()!=null && castOther.getPagecode()!=null && this.getPagecode().equals(castOther.getPagecode()) ) )
 && ( (this.getTaskcode()==castOther.getTaskcode()) || ( this.getTaskcode()!=null && castOther.getTaskcode()!=null && this.getTaskcode().equals(castOther.getTaskcode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPagecode() == null ? 0 : this.getPagecode().hashCode() );
         result = 37 * result + ( getTaskcode() == null ? 0 : this.getTaskcode().hashCode() );
         return result;
   }   


}


