package com.rawmakyamu.util.mapping;
// Generated Jan 28, 2016 9:45:39 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "STATUS")
public class Status implements java.io.Serializable {

    private String statuscode;
    private Statuscategory statuscategory;
    private String description;
    private Set<Task> tasks = new HashSet<Task>(0);
    private Set<Section> sections = new HashSet<Section>(0);
    private Set<Userrole> userroles = new HashSet<Userrole>(0);
    private Set<Systemuser> systemusers = new HashSet<Systemuser>(0);
    private Set<Page> pages = new HashSet<Page>(0);

    public Status() {
    }

    public Status(String statuscode) {
        this.statuscode = statuscode;
    }

    public Status(String statuscode, Statuscategory statuscategory, String description, Set<Task> tasks, Set<Section> sections,
            Set<Userrole> userroles,
            Set<Systemuser> systemusers,
            Set<Page> pages) {

        this.statuscode = statuscode;
        this.statuscategory = statuscategory;
        this.description = description;
        this.tasks = tasks;
        this.sections = sections;
        this.userroles = userroles;
        this.systemusers = systemusers;
        this.pages = pages;

    }

    @Id
    @Column(name = "STATUSCODE", unique = true, nullable = false, length = 10)
    public String getStatuscode() {
        return this.statuscode;
    }

    public void setStatuscode(String statuscode) {
        this.statuscode = statuscode;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CATEGORYCODE")
    public Statuscategory getStatuscategory() {
        return this.statuscategory;
    }

    public void setStatuscategory(Statuscategory statuscategory) {
        this.statuscategory = statuscategory;
    }

    @Column(name = "DESCRIPTION", length = 64)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
    public Set<Task> getTasks() {
        return this.tasks;
    }

    public void setTasks(Set<Task> tasks) {
        this.tasks = tasks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
    public Set<Section> getSections() {
        return this.sections;
    }

    public void setSections(Set<Section> sections) {
        this.sections = sections;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
    public Set<Userrole> getUserroles() {
        return this.userroles;
    }

    public void setUserroles(Set<Userrole> userroles) {
        this.userroles = userroles;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
    public Set<Systemuser> getSystemusers() {
        return this.systemusers;
    }

    public void setSystemusers(Set<Systemuser> systemusers) {
        this.systemusers = systemusers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
    public Set<Page> getPages() {
        return this.pages;
    }

    public void setPages(Set<Page> pages) {
        this.pages = pages;
    }

}
