package com.rawmakyamu.util.mapping;
// Generated Jan 28, 2016 9:45:39 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Statuscategory generated by hbm2java
 */
@Entity
@Table(name="STATUSCATEGORY"
   
    
)
public class Statuscategory  implements java.io.Serializable {


     private String categorycode;
     private String description;
     private Set<Status> statuses = new HashSet<Status>(0);

    public Statuscategory() {
    }

	
    public Statuscategory(String categorycode) {
        this.categorycode = categorycode;
    }
    public Statuscategory(String categorycode, String description, Set<Status> statuses) {
       this.categorycode = categorycode;
       this.description = description;
       this.statuses = statuses;
    }
   
     @Id 

    
    @Column(name="CATEGORYCODE", unique=true, nullable=false, length=10)
    public String getCategorycode() {
        return this.categorycode;
    }
    
    public void setCategorycode(String categorycode) {
        this.categorycode = categorycode;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="statuscategory")
    public Set<Status> getStatuses() {
        return this.statuses;
    }
    
    public void setStatuses(Set<Status> statuses) {
        this.statuses = statuses;
    }




}


