package com.rawmakyamu.util.mapping;
// Generated Jan 28, 2016 9:45:39 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Systemaudit generated by hbm2java
 */
@Entity
@Table(name="SYSTEMAUDIT"
    
    
)
public class Systemaudit  implements java.io.Serializable {


     private long systemauditid;
     private String userrolecode;
     private String sectioncode;
     private String pagecode;
     private String taskcode;
     private String ip;
     private String oldvalue;
     private String newvalue;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createtime;
     private String description;

    public Systemaudit() {
    }

	
    public Systemaudit(long systemauditid) {
        this.systemauditid = systemauditid;
    }
    public Systemaudit(long systemauditid, String userrolecode, String sectioncode, String pagecode, String taskcode, String description, String ip, String oldvalue, String newvalue, String lastupdateduser, Date lastupdatedtime, Date createtime) {
       this.systemauditid = systemauditid;
       this.userrolecode = userrolecode;
       this.sectioncode = sectioncode;
       this.pagecode = pagecode;
       this.taskcode = taskcode;
       this.ip = ip;
       this.oldvalue = oldvalue;
       this.newvalue = newvalue;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createtime = createtime;
       this.description = description;
    }
   
     @Id 
    
    @SequenceGenerator(name = "SequenceIdGenerator", sequenceName = "SYSTEMAUDIT_SEQ")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SequenceIdGenerator")
     
    @Column(name="SYSTEMAUDITID", unique=true, nullable=false, precision=22, scale=0)
    public long getSystemauditid() {
        return this.systemauditid;
    }
    
    public void setSystemauditid(long systemauditid) {
        this.systemauditid = systemauditid;
    }

    
    @Column(name="USERROLECODE", length=20)
    public String getUserrolecode() {
        return this.userrolecode;
    }
    
    public void setUserrolecode(String userrolecode) {
        this.userrolecode = userrolecode;
    }

    
    @Column(name="SECTIONCODE", length=20)
    public String getSectioncode() {
        return this.sectioncode;
    }
    
    public void setSectioncode(String sectioncode) {
        this.sectioncode = sectioncode;
    }

    
    @Column(name="PAGECODE", length=20)
    public String getPagecode() {
        return this.pagecode;
    }
    
    public void setPagecode(String pagecode) {
        this.pagecode = pagecode;
    }

    
    @Column(name="TASKCODE", length=20)
    public String getTaskcode() {
        return this.taskcode;
    }
    
    public void setTaskcode(String taskcode) {
        this.taskcode = taskcode;
    }

    
    @Column(name="IP", length=64)
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }

    
    @Column(name = "DESCRIPTION")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="OLDVALUE", length=4000)
    public String getOldvalue() {
        return this.oldvalue;
    }
    
    public void setOldvalue(String oldvalue) {
        this.oldvalue = oldvalue;
    }

    
    @Column(name="NEWVALUE", length=4000)
    public String getNewvalue() {
        return this.newvalue;
    }
    
    public void setNewvalue(String newvalue) {
        this.newvalue = newvalue;
    }

    
    @Column(name="LASTUPDATEDUSER", length=20)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=23)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATETIME", length=23)
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }




}


