package com.rawmakyamu.util.mapping;
// Generated Jan 28, 2016 9:45:39 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Systemuser generated by hbm2java
 */
@Entity
@Table(name="SYSTEMUSER"
   
)
public class Systemuser  implements java.io.Serializable {


     private String username;
     private Userrole userrole;
     private Status status;
//     private String systemuserid;
     private String password;
     private String empid;
     private String nic;
     private String city;
     private Date dateofbirth;
     private Date expirydate;
     private String fullname;
     private String address;
     private String mobile;
     private String email;
     private String dualauthuserrole;
     private String noofinvlidattempt;
     private Date loggeddate;
     private String initialloginstatus;
     private String lastupdateduser;
     private Date lastupdatedtime;
     private Date createtime;

    public Systemuser() {
    }

	
    public Systemuser(String username, String systemuserid) {
        this.username = username;
//        this.systemuserid = systemuserid;
    }
    public Systemuser(String username, String nic, String city, Date dateofbirth, Userrole userrole, Status status, String password, String empid, Date expirydate, String fullname, String address, String mobile, String email, String dualauthuserrole, String noofinvlidattempt, Date loggeddate, String initialloginstatus, String lastupdateduser, Date lastupdatedtime, Date createtime) {
       this.username = username;
       this.userrole = userrole;
       this.status = status;
       this.nic = nic;
       this.city = city;
       this.dateofbirth = dateofbirth;
//       this.systemuserid = systemuserid;
       this.password = password;
       this.empid = empid;
       this.expirydate = expirydate;
       this.fullname = fullname;
       this.address = address;
       this.mobile = mobile;
       this.email = email;
       this.dualauthuserrole = dualauthuserrole;
       this.noofinvlidattempt = noofinvlidattempt;
       this.loggeddate = loggeddate;
       this.initialloginstatus = initialloginstatus;
       this.lastupdateduser = lastupdateduser;
       this.lastupdatedtime = lastupdatedtime;
       this.createtime = createtime;
    }
   
     @Id 

    
    @Column(name="USERNAME", unique=true, nullable=false, length=20)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERROLECODE")
    public Userrole getUserrole() {
        return this.userrole;
    }
    
    public void setUserrole(Userrole userrole) {
        this.userrole = userrole;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUSCODE")
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
//    @Column(name="SYSTEMUSERID", nullable=false, length=20)
//    public String getSystemuserid() {
//        return this.systemuserid;
//    }
//    
//    public void setSystemuserid(String systemuserid) {
//        this.systemuserid = systemuserid;
//    }

    
    @Column(name="PASSWORD", length=64)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="EMPID", length=20)
    public String getEmpid() {
        return this.empid;
    }
    
    public void setEmpid(String empid) {
        this.empid = empid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXPIRYDATE", length=23)
    public Date getExpirydate() {
        return this.expirydate;
    }
    
    public void setExpirydate(Date expirydate) {
        this.expirydate = expirydate;
    }

    
    @Column(name="FULLNAME", length=128)
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    
    @Column(name="ADDRESS", length=64)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="MOBILE", length=20)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="EMAIL", length=128)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="DUALAUTHUSERROLE", length=20)
    public String getDualauthuserrole() {
        return this.dualauthuserrole;
    }
    
    public void setDualauthuserrole(String dualauthuserrole) {
        this.dualauthuserrole = dualauthuserrole;
    }

    
    @Column(name="NOOFINVLIDATTEMPT", length=20)
    public String getNoofinvlidattempt() {
        return this.noofinvlidattempt;
    }
    
    public void setNoofinvlidattempt(String noofinvlidattempt) {
        this.noofinvlidattempt = noofinvlidattempt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LOGGEDDATE", length=23)
    public Date getLoggeddate() {
        return this.loggeddate;
    }
    
    public void setLoggeddate(Date loggeddate) {
        this.loggeddate = loggeddate;
    }

    
    @Column(name="INITIALLOGINSTATUS", length=20)
    public String getInitialloginstatus() {
        return this.initialloginstatus;
    }
    
    public void setInitialloginstatus(String initialloginstatus) {
        this.initialloginstatus = initialloginstatus;
    }

    
    @Column(name="LASTUPDATEDUSER", length=20)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=23)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATETIME", length=23)
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

     @Column(name="NIC", length=10)
    public String getNic() {
        return nic;
    }

    public void setNic(String nic) {
        this.nic = nic;
    }

     @Column(name="CITY", length=40)
    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATEOFBIRTH", length=23)
    public Date getDateofbirth() {
        return dateofbirth;
    }

    public void setDateofbirth(Date dateofbirth) {
        this.dateofbirth = dateofbirth;
    }

    



}


