package com.rawmakyamu.util.mapping;
// Generated Jan 28, 2016 9:45:39 AM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "SBANK_TRANSACTION"
)
public class Transaction implements java.io.Serializable {

    private String transactionid;
    private String cardnumber;
    private String txntypecode;
    private String walletid;
    private String amount;
    private String towallet;
    private String deviceid;
    private String approvecode;
    private String mobile;
    private String rrn;
    private String tid;
    private String currency;
    private String listeneruid;
    private String mid;
    private String maskingcard;
    private String tocardnumber;
    private String tomaskingcard;
    private String mti;
    private String processingcode;
    private String localdate;
    private String localtime;
    private String posentrymode;
    private String nii;
    private String nic;
    private String posconditioncode;
    private String cardexpiredate;
    private String invoiceno;
    private String tracenumber;
    private String responcecode;
    private String switchresponse;
    private Status status;
    private String lastupdateduser;
    private Date createtime;
    private Date lastupdatedtime;
    private String tokenid;
    private String toAccount;
    private String fromAccount;
    private String toEmail;
    private Status approvalStatus;
    private String cardType;
    private String tomobile;
    private String promoAmount;
    private String commissionAmount;
    private String deductAmount;
    private String cardBrand;

    public Transaction() {
    }

    public Transaction(String transactionid) {
        this.transactionid = transactionid;
    }

    public Transaction(String nic, String switchresponse, String transactionid, String mobile, String currency, String listeneruid, String maskingcard, String tocardnumber, String tomaskingcard, String tid, String mid, String cardexpiredate, String invoiceno, String posconditioncode, String nii, String posentrymode, String localtime, String localdate, String processingcode, String mti, String cardnumber, String txntypecode, String walletid, String amount, String towallet, String deviceid, String approvecode, String rrn, String tracenumber, String responcecode, Status status, String lastupdateduser, Date lastupdatedtime, Date createtime, String tokenid, String toAccount, String fromAccount, String cardType, String tomobile, String cardBrand) {
//    public Transaction(String nic,Switchresponse switchresponse,String transactionid, String mobile, Currency currency, String listeneruid, String maskingcard, String tocardnumber, String tomaskingcard, String tid, String mid, String cardexpiredate, String invoiceno, String posconditioncode, String nii, String posentrymode, String localtime, String localdate, String processingcode, String mti, String cardnumber, Transactiontype txntypecode, String walletid, String amount, String towallet, String deviceid, String approvecode, String rrn, String tracenumber, String responcecode, Status status, String lastupdateduser, Date lastupdatedtime, Date createtime) {
//    public Transaction(String nic,String transactionid, String mobile, Currency currency, String listeneruid, String maskingcard, String tocardnumber, String tomaskingcard, String tid, String mid, String cardexpiredate, String invoiceno, String posconditioncode, String nii, String posentrymode, String localtime, String localdate, String processingcode, String mti, String cardnumber, Transactiontype txntypecode, String walletid, String amount, String towallet, String deviceid, String approvecode, String rrn, String tracenumber, String responcecode, Status status, String lastupdateduser, Date lastupdatedtime, Date createtime) {
        this.transactionid = transactionid;
        this.cardnumber = cardnumber;
        this.txntypecode = txntypecode;
        this.walletid = walletid;
        this.amount = amount;
        this.towallet = towallet;
        this.deviceid = deviceid;
        this.approvecode = approvecode;
        this.rrn = rrn;
        this.tracenumber = tracenumber;
        this.responcecode = responcecode;
        this.status = status;
        this.lastupdateduser = lastupdateduser;
        this.lastupdatedtime = lastupdatedtime;
        this.createtime = createtime;
        this.mti = mti;
        this.processingcode = processingcode;
        this.localdate = localdate;
        this.localtime = localtime;
        this.posentrymode = posentrymode;
        this.nii = nii;
        this.nic = nic;
        this.tid = tid;
        this.mid = mid;
        this.maskingcard = maskingcard;
        this.tocardnumber = tocardnumber;
        this.tomaskingcard = tomaskingcard;
        this.posconditioncode = posconditioncode;
        this.cardexpiredate = cardexpiredate;
        this.invoiceno = invoiceno;
        this.currency = currency;
        this.listeneruid = listeneruid;
        this.mobile = mobile;
        this.switchresponse = switchresponse;
        this.tokenid = tokenid;
        this.toAccount = toAccount;
        this.fromAccount = fromAccount;
        this.tomobile = tomobile;
        this.cardBrand = cardBrand;
    }

    @Id

    @Column(name = "TRANSACTIONID", unique = true, nullable = false, length = 20)
    public String getTransactionid() {
        return this.transactionid;
    }

    public void setTransactionid(String transactionid) {
        this.transactionid = transactionid;
    }

    @Column(name = "MASKING_CARD", length = 20)
    public String getMaskingcard() {
        return maskingcard;
    }

    public void setMaskingcard(String maskingcard) {
        this.maskingcard = maskingcard;
    }

    @Column(name = "TO_CARDNUMBER", length = 50)
    public String getTocardnumber() {
        return tocardnumber;
    }

    public void setTocardnumber(String tocardnumber) {
        this.tocardnumber = tocardnumber;
    }

    @Column(name = "TO_MASKING_CARD", length = 20)
    public String getTomaskingcard() {
        return tomaskingcard;
    }

    public void setTomaskingcard(String tomaskingcard) {
        this.tomaskingcard = tomaskingcard;
    }

    @Column(name = "CARDNUMBER", length = 50)
    public String getCardnumber() {
        return this.cardnumber;
    }

    public void setCardnumber(String cardnumber) {
        this.cardnumber = cardnumber;
    }

//    @ManyToOne(fetch=FetchType.LAZY)
//    @JoinColumn(name="TXNTYPECODE")
    @Column(name = "TXNTYPECODE", length = 10)
    public String getTxntypecode() {
        return this.txntypecode;
    }

    public void setTxntypecode(String txntypecode) {
        this.txntypecode = txntypecode;
    }

    @Column(name = "WALLETID", length = 10)
    public String getWalletid() {
        return this.walletid;
    }

    public void setWalletid(String walletid) {
        this.walletid = walletid;
    }

    @Column(name = "AMOUNT", length = 20)
    public String getAmount() {
        return this.amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    @Column(name = "TOWALLET", length = 10)
    public String getTowallet() {
        return this.towallet;
    }

    public void setTowallet(String towallet) {
        this.towallet = towallet;
    }

    @Column(name = "DEVICEID", length = 200)
    public String getDeviceid() {
        return this.deviceid;
    }

    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid;
    }

    @Column(name = "APPROVECODE", length = 20)
    public String getApprovecode() {
        return this.approvecode;
    }

    public void setApprovecode(String approvecode) {
        this.approvecode = approvecode;
    }

    @Column(name = "TID", length = 8)
    public String getTid() {
        return tid;
    }

    public void setTid(String tid) {
        this.tid = tid;
    }

    @Column(name = "MID", length = 15)
    public String getMid() {
        return mid;
    }

    public void setMid(String mid) {
        this.mid = mid;
    }

    @Column(name = "RRN", length = 50)
    public String getRrn() {
        return this.rrn;
    }

    public void setRrn(String rrn) {
        this.rrn = rrn;
    }

    @Column(name = "TRACENUMBER", length = 50)
    public String getTracenumber() {
        return this.tracenumber;
    }

    public void setTracenumber(String tracenumber) {
        this.tracenumber = tracenumber;
    }

//    @Column(name="RESPONCECODE", length=20)
//    public String getResponcecode() {
//        return this.responcecode;
//    }
//    
//    public void setResponcecode(String responcecode) {
//        this.responcecode = responcecode;
//    }
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUS")
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @Column(name = "LASTUPDATEDUSER", length = 20)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }

    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LASTUPDATEDTIME", length = 23)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }

    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATETIME", length = 23)
    public Date getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    @Column(name = "MTI", length = 4)
    public String getMti() {
        return mti;
    }

    public void setMti(String mti) {
        this.mti = mti;
    }

    @Column(name = "PROCESSINGCODE", length = 6)
    public String getProcessingcode() {
        return processingcode;
    }

    public void setProcessingcode(String processingcode) {
        this.processingcode = processingcode;
    }

    @Column(name = "LOCALDATE", length = 4)
    public String getLocaldate() {
        return localdate;
    }

    public void setLocaldate(String localdate) {
        this.localdate = localdate;
    }

    @Column(name = "LOCALTIME", length = 6)
    public String getLocaltime() {
        return localtime;
    }

    public void setLocaltime(String localtime) {
        this.localtime = localtime;
    }

    @Column(name = "POSENTRYMODE", length = 6)
    public String getPosentrymode() {
        return posentrymode;
    }

    public void setPosentrymode(String posentrymode) {
        this.posentrymode = posentrymode;
    }

    @Column(name = "NII", length = 4)
    public String getNii() {
        return nii;
    }

    public void setNii(String nii) {
        this.nii = nii;
    }

    @Column(name = "POSCONDITIONCODE", length = 2)
    public String getPosconditioncode() {
        return posconditioncode;
    }

    public void setPosconditioncode(String posconditioncode) {
        this.posconditioncode = posconditioncode;
    }

    @Column(name = "CARDEXPIREDATE", length = 4)
    public String getCardexpiredate() {
        return cardexpiredate;
    }

    public void setCardexpiredate(String cardexpiredate) {
        this.cardexpiredate = cardexpiredate;
    }

    @Column(name = "INVOICENO", length = 6)
    public String getInvoiceno() {
        return invoiceno;
    }

    public void setInvoiceno(String invoiceno) {
        this.invoiceno = invoiceno;
    }

//    @ManyToOne(fetch=FetchType.LAZY)
//    @JoinColumn(name="CURRENCYCODE")
    @Column(name = "CURRENCYCODE", length = 10)
    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    @Column(name = "LISTNERUID", length = 4)
    public String getListeneruid() {
        return listeneruid;
    }

    public void setListeneruid(String listeneruid) {
        this.listeneruid = listeneruid;
    }

    @Column(name = "MOBILENUMBER", length = 20)
    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

//    @ManyToOne(fetch=FetchType.LAZY)
//    @JoinColumn(name="RESPONCECODE")
    @Column(name = "RESPONCECODE", length = 10)
    public String getSwitchresponse() {
        return switchresponse;
    }

    public void setSwitchresponse(String switchresponse) {
        this.switchresponse = switchresponse;
    }

    @Column(name = "TOKEN_ID", length = 20)
    public String getTokenid() {
        return tokenid;
    }

    public void setTokenid(String tokenid) {
        this.tokenid = tokenid;
    }

    @Column(name = "TO_ACCOUNT", length = 20)
    public String getToAccount() {
        return this.toAccount;
    }

    public void setToAccount(String toAccount) {
        this.toAccount = toAccount;

    }

    @Column(name = "FROM_ACCOUNT", length = 20)
    public String getFromAccount() {
        return this.fromAccount;
    }

    public void setFromAccount(String fromAccount) {
        this.fromAccount = fromAccount;
    }

    @Column(name = "TO_EMAIL", length = 100)
    public String getToEmail() {
        return toEmail;
    }

    public void setToEmail(String toEmail) {
        this.toEmail = toEmail;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "APPROVAL_STATUS")
    public Status getApprovalStatus() {
        return approvalStatus;
    }

    public void setApprovalStatus(Status approvalStatus) {
        this.approvalStatus = approvalStatus;
    }

    @Column(name = "CARD_TYPE", length = 2)
    public String getCardType() {
        return this.cardType;
    }

    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    @Column(name = "TOMOBILE", length = 20)
    public String getTomobile() {
        return tomobile;
    }

    public void setTomobile(String tomobile) {
        this.tomobile = tomobile;
    }

    @Column(name = "PROMO_AMOUNT", length = 20)
    public String getPromoAmount() {
        return promoAmount;
    }

    public void setPromoAmount(String promoAmount) {
        this.promoAmount = promoAmount;
    }

    @Column(name = "COMM_AMOUNT", length = 20)
    public String getCommissionAmount() {
        return commissionAmount;
    }

    public void setCommissionAmount(String commissionAmount) {
        this.commissionAmount = commissionAmount;
    }

    @Column(name = "DEDUCT_AMOUNT", length = 20)
    public String getDeductAmount() {
        return deductAmount;
    }

    public void setDeductAmount(String deductAmount) {
        this.deductAmount = deductAmount;
    }

    @Column(name = "CARD_BRAND", length = 2)
    public String getCardBrand() {
        return this.cardBrand;
    }

    public void setCardBrand(String cardBrand) {
        this.cardBrand = cardBrand;
    }

}
