package com.rawmakyamu.util.mapping;
// Generated Jan 28, 2016 9:45:39 AM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transactionhistory generated by hbm2java
 */
@Entity
@Table(name = "TRANSACTIONHISTORY"
)
public class Transactionhistory implements java.io.Serializable {

    private String transactionhistoryid;
    private String transactionid;
    private String status;
    private Date createtime;

    public Transactionhistory() {
    }

    public Transactionhistory(String transactionhistoryid) {
        this.transactionhistoryid = transactionhistoryid;
    }

    public Transactionhistory(String transactionhistoryid, String transactionid, String status, Date createtime) {
        this.transactionhistoryid = transactionhistoryid;
        this.transactionid = transactionid;
        this.status = status;
        this.createtime = createtime;
    }

    @Id

    @Column(name = "TRANSACTIONHISTORYID", unique = true, nullable = false, length = 30)
    public String getTransactionhistoryid() {
        return this.transactionhistoryid;
    }

    public void setTransactionhistoryid(String transactionhistoryid) {
        this.transactionhistoryid = transactionhistoryid;
    }

    @Column(name = "TRANSACTIONID", length = 20)
    public String getTransactionid() {
        return this.transactionid;
    }

    public void setTransactionid(String transactionid) {
        this.transactionid = transactionid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATETIME", length = 23)
    public Date getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    @Column(name = "STATUS", length = 20)
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
