package com.rawmakyamu.util.mapping;
// Generated Jan 28, 2016 9:45:39 AM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Transactiontype generated by hbm2java
 */
@Entity
@Table(name = "TRANSACTIONTYPE"
)
public class Transactiontype implements java.io.Serializable {

    private String typecode;
    private String description;
    private Status status;
    private String otpRequired;
    private String riskRequired;
    private String acqRiskRequired;
    private String merchantTxnType;
    private String description_receiver;
    private String history_visibility;
    private Byte sortOrder;

    public Transactiontype() {
    }

    public Transactiontype(String typecode) {
        this.typecode = typecode;
    }

    public Transactiontype(String typecode, String description_receiver, String history_visibility, String description, Status status, String otpRequired, String riskRequired, String acqRiskRequired, String merchantTxnType, Byte sortOrder) {//Set<Risktransactionprofile> transactionprofile, 
        this.typecode = typecode;
        this.description = description;
        this.status = status;
        this.otpRequired = otpRequired;
        this.riskRequired = riskRequired;
        this.acqRiskRequired = acqRiskRequired;
        this.merchantTxnType = merchantTxnType;
        this.description_receiver = description_receiver;
        this.history_visibility = history_visibility;
        this.sortOrder = sortOrder;
    }

    @Id

    @Column(name = "TYPECODE", unique = true, nullable = false, length = 3)
    public String getTypecode() {
        return this.typecode;
    }

    public void setTypecode(String typecode) {
        this.typecode = typecode;
    }

    @Column(name = "DESCRIPTION", length = 10)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "STATUS")
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @Column(name = "OTP_REQUIRED", length = 10)
    public String getOtpRequired() {
        return this.otpRequired;
    }

    public void setOtpRequired(String otpRequired) {
        this.otpRequired = otpRequired;
    }

    @Column(name = "RISK_REQUIRED", length = 10)
    public String getRiskRequired() {
        return riskRequired;
    }

    public void setRiskRequired(String riskRequired) {
        this.riskRequired = riskRequired;
    }

    @Column(name = "ACQ_RISK_REQUIRED", length = 20)
    public String getAcqRiskRequired() {
        return acqRiskRequired;
    }

    public void setAcqRiskRequired(String acqRiskRequired) {
        this.acqRiskRequired = acqRiskRequired;
    }

    @Column(name = "MERCHANT_TXN_TYPE", length = 20)

    public String getMerchantTxnType() {
        return this.merchantTxnType;
    }

    public void setMerchantTxnType(String merchantTxnType) {
        this.merchantTxnType = merchantTxnType;
    }

    @Column(name = "DESCRIPTION_RECEIVER", length = 64)
    public String getDescription_receiver() {
        return description_receiver;
    }

    public void setDescription_receiver(String description_receiver) {
        this.description_receiver = description_receiver;
    }

    @Column(name = "HISTORY_VISIBILITY", length = 5)
    public String getHistory_visibility() {
        return history_visibility;
    }

    public void setHistory_visibility(String history_visibility) {
        this.history_visibility = history_visibility;
    }

    @Column(name = "SORT_ORDER", precision = 2, scale = 0)
    public Byte getSortOrder() {
        return sortOrder;
    }

    public void setSortOrder(Byte sortOrder) {
        this.sortOrder = sortOrder;
    }

}
