package com.rawmakyamu.util.mapping;
// Generated Jan 28, 2016 9:45:39 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserrolesectionId generated by hbm2java
 */
@Embeddable
public class UserrolesectionId  implements java.io.Serializable {


     private String userrolecode;
     private String sectioncode;

    public UserrolesectionId() {
    }

    public UserrolesectionId(String userrolecode, String sectioncode) {
       this.userrolecode = userrolecode;
       this.sectioncode = sectioncode;
    }
   


    @Column(name="USERROLECODE", nullable=false, length=20)
    public String getUserrolecode() {
        return this.userrolecode;
    }
    
    public void setUserrolecode(String userrolecode) {
        this.userrolecode = userrolecode;
    }


    @Column(name="SECTIONCODE", nullable=false, length=20)
    public String getSectioncode() {
        return this.sectioncode;
    }
    
    public void setSectioncode(String sectioncode) {
        this.sectioncode = sectioncode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserrolesectionId) ) return false;
		 UserrolesectionId castOther = ( UserrolesectionId ) other; 
         
		 return ( (this.getUserrolecode()==castOther.getUserrolecode()) || ( this.getUserrolecode()!=null && castOther.getUserrolecode()!=null && this.getUserrolecode().equals(castOther.getUserrolecode()) ) )
 && ( (this.getSectioncode()==castOther.getSectioncode()) || ( this.getSectioncode()!=null && castOther.getSectioncode()!=null && this.getSectioncode().equals(castOther.getSectioncode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserrolecode() == null ? 0 : this.getUserrolecode().hashCode() );
         result = 37 * result + ( getSectioncode() == null ? 0 : this.getSectioncode().hashCode() );
         return result;
   }   


}


